sources:
  - test_name_1/Sources
templates:
  - tools/sourcery/templates
output:
  test_name_1Tests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - test_name_1
  autoMockableImports:
    - RxSwift
    - RxCocoa
