import ProjectDescription

let workspace = Workspace.workspace(name: "test_name_1")

extension Workspace {

    static func workspace(name: String) -> Workspace {
        return Workspace(
            name: name,
            projects: ["./**"],
            generationOptions: .options(
                autogeneratedWorkspaceSchemes:
                        .disabled
            )
        )
    }
}
